<!DOCTYPE dvdlibrary
        [
        <!ELEMENT dvdlibrary (dvd+)>
<!ELEMENT dvd (title, description, year, company, characters, bonus, purchased)>
<!ATTLIST dvd isbn CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT company (#PCDATA)>

<!ELEMENT characters (character+)>
<!ELEMENT character (#PCDATA)>

<!ELEMENT bonus (feature+)>
<!ATTLIST bonus num CDATA #REQUIRED>
<!ELEMENT feature (#PCDATA)>


<!ELEMENT purchased (price, location, date)>
<!ATTLIST purchased from (mom | dad | sister | grandpa | grandma) #IMPLIED>
<!ELEMENT price (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT date (#PCDATA)>
        ]>

<dvdlibrary>
    <dvd isbn="5655856548484">
        <title>Howls Moving Castle</title>
        <description>Story about a girl bewitched into an old women.</description>
        <year>2004</year>
        <company>Warner Brothers</company>
        <characters>
            <character>Howl</character>
            <character>Sophie</character>
        </characters>
        <bonus num="1">
            <feature>Bonus Disc</feature>
        </bonus>
        <purchased>
            <price>$15.00</price>
            <location>Borders</location>
            <date>Aug 24, 2008</date>
        </purchased>
    </dvd>
    <dvd isbn="654564894894">
        <title>Toy Story</title>
        <description>Animated movie about toys coming to life.</description>
        <year>1996</year>
        <company>Pixar</company>
        <characters>
            <character>Woody</character>
            <character>Peep</character>
            <character>Buzz</character>
            <character>Andy</character>
        </characters>
        <bonus num="1">
            <feature>Outtakes</feature>
        </bonus>
        <purchased from="grandma">
            <price>$0.00</price>
            <location>N/A</location>
            <date>02/20/2002</date>
        </purchased>
    </dvd>
    <dvd isbn="239482847575">
        <title>Star Wars: Force Awakens</title>
        <description>Jedi forces are back with Luke missing.</description>
        <year>2015</year>
        <company>LucasFilm</company>
        <characters>
            <character>Rey</character>
            <character>Poe Dameron</character>
            <character>Finn</character>
            <character>Leia Organa-Solo</character>
            <character>Kylo Ren</character>
        </characters>
        <bonus num="4">
            <feature>Outtakes</feature>
            <feature>Deleted Scenes</feature>
            <feature>Bloopers</feature>
            <feature>Directors Commentary</feature>
        </bonus>
        <purchased>
            <price>$23.00</price>
            <location>Amazon</location>
            <date>05/24/2016</date>
        </purchased>
    </dvd>
</dvdlibrary>